version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-23.11"

sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: false

conda:
  environment: envs/environment-rtd.yaml

# Only build HTML and JSON formats
formats: []
