# conda environment description file for salishsea_site package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the salishsea_site web app with:
#
#    $ cd salishsea_site
#    $ conda env create -f environment-dev.yaml
#    $ source activate salishsea_site
#    $ pip install --editable .

name: salishsea-site

dependencies:
  - pip
  - python=3
  - pyyaml
  - requests

  # For unit tests
  - coverage
  - pytest

  # For documentation and building old static site
  - sphinx

  - pip:
    - arrow
    - attrs
    - chaussette
    - circus
    - pyramid
    - pyramid_crow
    - pyramid_debugtoolbar
    - pyramid_mako
    - waitress==0.9.0

    # For building old static site
    - sphinx-bootstrap-theme
