# conda environment description file for docs build environment
# on readthedocs.org

name: sphinx-build

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10

  # readthedocs packages
  - mock
  - pillow
  - pip
  - sphinx=7.2.6
  - sphinx-notfound-page=1.0.0
  - sphinx-rtd-theme=2.0.0

  - pip:
    - pyramid
    - sentry_sdk

    # readthedocs packages
    - recommonmark
    - readthedocs-sphinx-ext
