# conda environment description file for docs build environment
# on readthedocs.org

name: salishsea-site-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10

  # Sphinx and extensions we use
  - sphinx=7.2.6
  - sphinx-notfound-page=1.0.0
  - sphinx-rtd-theme=2.0.0

  # readthedocs build system packages
  - mock
  - pillow
  - pip:
    - commonmark
    - recommonmark
    - readthedocs-sphinx-ext

    - pyramid
    - sentry_sdk
