# conda environment description file for docs build envioronment
# on readthedocs.org

name: sphinx-build

channels:
  - defaults

dependencies:
  - pip
  - python>=3.6
  - pip:
      - pyramid
      - sentry_sdk
