# conda environment description file for docs build environment
# on readthedocs.org

name: salishsea-site-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - python=3.12

  # Sphinx and extensions we use
  - sphinx==8.1.3
  - sphinx-notfound-page==1.0.4
  - sphinx-rtd-theme==3.0.0

  # readthedocs build system packages
  - mock
  - pillow
  - pip:
    - commonmark
    - recommonmark
    - readthedocs-sphinx-ext

    - pyramid
    - sentry_sdk

    # Install salishsea-site package in editable mode
    - --editable ../
