# conda environment description file for salishsea_site package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the salishsea_site web app with:
#
#    $ cd salishsea_site
#    $ conda env create -f envs/environment-dev.yaml
#    $ source activate salishsea-site
#    (salishsea-site)$ python3 -m pip install --editable .

name: salishsea-site

channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - python=3.10
  - pyyaml
  - requests

  # For coding style
  - black

  # For unit tests
  - pytest
  - pytest-cov
  - tomli

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - arrow
    - attrs
    - pyramid
    - pyramid_debugtoolbar
    - pyramid_mako
    - sentry-sdk
    - supervisor
    - waitress
