# conda environment description file for salishsea_site package
# production deployment
#
# Create a conda environment for production deployment of the
# salishsea_site web app with:
#
#    $ cd salishsea_site
#    $ conda env create -f envs/environment-prod.yaml

name: salishsea-site-env

channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - python=3.12
  - pyyaml
  - requests
  - pip:
    - arrow
    - attrs
    - pyramid
    - pyramid_mako
    - sentry-sdk
    - supervisor
    - waitress

    # install of salishsea-site package editable mode
    - --editable ../
