# conda environment description file for docs build environment
# on readthedocs.org

name: sphinx-build

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10

  # readthedocs packages
  - mock
  - pillow
  - pip
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - pyramid
    - sentry_sdk

    # readthedocs packages
    - recommonmark
    - readthedocs-sphinx-ext
