# conda environment description file for salishsea_site package
# production deployment
#
# Create a conda environment for production deployment of the
# salishsea_site web app with:
#
#    $ cd salishsea_site
#    $ conda env create -f envs/environment-prod.yaml
#    $ source activate salishsea_site
#    $ pip install --editable .

name: salishsea-site-env

channels:
  - conda-forge
  - defaults

dependencies:
  - pip
  - python>=3.6
  - pyyaml
  - requests
  - pip:
    - arrow
    - attrs
    - pyramid
    - pyramid_mako
    - sentry-sdk
    - supervisor
    - waitress
