# conda environment description file for salishsea_site package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the salishsea_site web app with:
#
#    $ cd salishsea_site
#    $ conda env create -f environment-dev.yaml
#    $ source activate salishsea_site
#    $ pip install --editable .

name: salishsea-site

channels:
  - conda-forge
  - defaults

dependencies:
  - pip
  - python>=3.6
  - pyyaml
  - requests

  # For coding style
  - black

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - arrow
    - attrs
    - pyramid
    - pyramid_debugtoolbar
    - pyramid_mako
    - sentry-sdk
    - supervisor
    - waitress
