name: sphinx-linkcheck

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
    - cron: 43 4 7 * *  # 04:43 UTC on the 7th day of each month

jobs:
  docs-linkcheck:
    name: linkcheck docs
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
           auto-update-conda: true
           auto-activate-base: false
           environment-file: envs/environment-test.yaml
           python-version: ${{ matrix.python-version }}
           activate-environment: salishsea-site-test

      - name: Install package
        shell: bash -l {0}
        run: |
          python3 -m pip install --editable $GITHUB_WORKSPACE

      - name: linkcheck docs
        shell: bash -l {0}
        run: |
          (cd docs && make linkcheck)

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Sphinx linkcheck
          fields: repo,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SALISHSEACAST_WEBHOOK_URL }}
        if: always()
