name: sphinx-linkcheck

on:
  push:
    branches:  [ '*' ]
  schedule:
    - cron: 43 4 7 * *  # 04:43 UTC on the 7th day of each month

jobs:
  docs-linkcheck:
    name: linkcheck docs
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        # Need to specify Python version here because we use test env which gets its
        # Python version via matrix
        python-version: [ '3.10' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
           miniforge-variant: Mambaforge-pypy3
           miniforge-version: latest
           use-mamba: true
           auto-update-conda: true
           auto-activate-base: false
           channels: conda-forge,nodefaults
           channel-priority: true
           python-version: ${{ matrix.python-version }}
           environment-file: envs/environment-test.yaml
           activate-environment: salishsea-site-test

      - name: Install package
        shell: bash -l {0}
        run: |
          python3 -m pip install --editable $GITHUB_WORKSPACE

      - name: linkcheck docs
        shell: bash -l {0}
        run: |
          (cd docs && make linkcheck)

      - name: Push job status to SalishSeaCast Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Sphinx linkcheck
          fields: repo,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SALISHSEACAST_WEBHOOK_URL }}
        if: always()
