name: CI

on:
  push:
    branches:  [ '*' ]

jobs:
  test-coverage:
    name: pytest & coverage report
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up conda environment and install salishsea-site package
        uses: conda-incubator/setup-miniconda@v2
        with:
           miniforge-variant: Mambaforge-pypy3
           miniforge-version: latest
           use-mamba: true
           auto-update-conda: true
           auto-activate-base: false
           channels: conda-forge,nodefaults
           channel-priority: true
           environment-file: envs/environment-test.yaml
           python-version: ${{ matrix.python-version }}
           activate-environment: salishsea-site-test

      - name: pytest package with coverage
        shell: bash -l {0}
        run: |
          pytest --cov=$GITHUB_WORKSPACE --cov-report=xml

      - name: Push job status to SalishSeaCast Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Python ${{ matrix.python-version }} pytest & coverage report
          fields: repo,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SALISHSEACAST_WEBHOOK_URL }}
        if: always()

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
        if: always()
