name: pytest-with-coverage

on:
  push:
    branches: [ '*' ]
  # Enable workflow to be triggered from GitHub CLI, browser, or via API
  # primarily for testing conda env solution for new Python versions
  workflow_dispatch:

jobs:
  pytest-with-coverage:
    permissions:
      contents: read
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    uses: UBC-MOAD/gha-workflows/.github/workflows/pytest-with-coverage.yaml@main
    with:
      python-version: ${{ matrix.python-version }}
      conda-env-file: envs/environment-test.yaml
      conda-env-name: salishsea-site-test
